#!/usr/bin/env node
// Copies ABIs from Foundry build artifacts (apps/contracts/out/) into typed
// TS modules the bot can import. Run `pnpm --filter contracts build` (forge
// build) first so apps/contracts/out/ is up to date.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const contractsOut = path.resolve(here, "../../contracts/out");
const abiOut = path.resolve(here, "../src/abi");

const targets = [
  { artifact: "StreamVaults.sol/StreamVaults.json", exportName: "streamVaultsAbi", file: "streamVaults.ts" },
  { artifact: "SmartAccountDCA.sol/SmartAccountDCA.json", exportName: "smartAccountDCAAbi", file: "smartAccountDCA.ts" },
  { artifact: "StreamVaultsConfig.sol/StreamVaultsConfig.json", exportName: "streamVaultsConfigAbi", file: "streamVaultsConfig.ts" },
];

for (const { artifact, exportName, file } of targets) {
  const artifactPath = path.join(contractsOut, artifact);
  if (!existsSync(artifactPath)) {
    console.error(
      `Missing ${artifactPath}. Run "pnpm --filter contracts build" (forge build) first.`,
    );
    process.exitCode = 1;
    continue;
  }
  const { abi } = JSON.parse(readFileSync(artifactPath, "utf8"));
  const banner = "// Auto-generated by scripts/sync-abis.mjs. Do not edit by hand.\n";
  const body = `${banner}export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(path.join(abiOut, file), body);
  console.log(`Wrote src/abi/${file} (${abi.length} entries)`);
}
