// Auto-generated by scripts/sync-abis.mjs. Do not edit by hand.
export const smartAccountDCAAbi = [
  {
    "type": "constructor",
    "inputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "receive",
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "executeSwap",
    "inputs": [
      {
        "name": "params",
        "type": "tuple",
        "internalType": "struct Types.SwapParams",
        "components": [
          {
            "name": "superTokenIn",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "superAmountIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "tokenIn",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "tokenOut",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "amountIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minAmountOut",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "amountOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "initialize",
    "inputs": [
      {
        "name": "owner_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "operator_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "initializeWithRules",
    "inputs": [
      {
        "name": "owner_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "operator_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "rules_",
        "type": "tuple",
        "internalType": "struct Types.UserRules",
        "components": [
          {
            "name": "maxSlippageBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minTradeAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "settlementAddress",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "targetTokens",
            "type": "address[]",
            "internalType": "address[]"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isTargetToken",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "operator",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "rules",
    "inputs": [],
    "outputs": [
      {
        "name": "maxSlippageBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "minTradeAmount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "settlementAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setRules",
    "inputs": [
      {
        "name": "rules_",
        "type": "tuple",
        "internalType": "struct Types.UserRules",
        "components": [
          {
            "name": "maxSlippageBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minTradeAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "settlementAddress",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "targetTokens",
            "type": "address[]",
            "internalType": "address[]"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "targetTokens",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "withdraw",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "withdrawAll",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "Executed",
    "inputs": [
      {
        "name": "router",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "tokenIn",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "tokenOut",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amountIn",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "amountOut",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Initialized",
    "inputs": [
      {
        "name": "version",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Initialized",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "operator",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RulesUpdated",
    "inputs": [
      {
        "name": "maxSlippageBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "minTradeAmount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "settlementAddress",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "targetTokens",
        "type": "address[]",
        "indexed": false,
        "internalType": "address[]"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Withdrawn",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "FORWARDER_NOT_SET",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INSUFFICIENT_OUTPUT",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_ADDRESS",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_AMOUNT",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_LABEL",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_LABEL_CHARS",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_RATE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_REPORT",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_RULES",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_SWAP_TOKEN",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_TARGET",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_THRESHOLD",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidInitialization",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LABEL_TAKEN",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LABEL_TOO_LONG",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NAME_ALREADY_REGISTERED",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NAME_NOT_FOUND",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NOT_BOT",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NOT_OPERATOR",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NOT_OWNER",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NOT_SMART_ACCOUNT_OWNER",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NO_PRICE_SOURCE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NO_STREAM_TO_CLOSE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotInitializing",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ORACLE_DEVIATION",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RATE_TOO_LOW",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RULES_NOT_SET",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SMART_ACCOUNT_ALREADY_EXISTS",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SMART_ACCOUNT_IMPL_NOT_SET",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SMART_ACCOUNT_NOT_FOUND",
    "inputs": []
  },
  {
    "type": "error",
    "name": "STALE_PRICE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "STREAM_NOT_ACTIVE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "STREAM_NOT_LOW",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SWAP_CALL_FAILED",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SWAP_COOLDOWN_ACTIVE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TARGET_TOKEN_NOT_ALLOWED",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TRADE_BELOW_MIN",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UNAUTHORIZED_CALLER",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UNSUPPORTED_UNDERLYING",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WINDOW_TOO_LOW",
    "inputs": []
  }
] as const;
