// Auto-generated by scripts/sync-abis.mjs. Do not edit by hand.
export const streamVaultsAbi = [
  {
    "type": "constructor",
    "inputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "UPGRADE_INTERFACE_VERSION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "closeStreamIfLow",
    "inputs": [
      {
        "name": "smartAccount",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "superToken",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "closed",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "config",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "createSmartAccount",
    "inputs": [],
    "outputs": [
      {
        "name": "smartAccount",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "executeSwap",
    "inputs": [
      {
        "name": "smartAccount",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "params",
        "type": "tuple",
        "internalType": "struct Types.SwapParams",
        "components": [
          {
            "name": "superTokenIn",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "superAmountIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "tokenIn",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "tokenOut",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "amountIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minAmountOut",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "amountOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "initialize",
    "inputs": [
      {
        "name": "owner_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "config_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "lastSwapBlock",
    "inputs": [
      {
        "name": "smartAccount",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "onboard",
    "inputs": [
      {
        "name": "superToken",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "underlyingAmount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "rate",
        "type": "int96",
        "internalType": "int96"
      },
      {
        "name": "rules",
        "type": "tuple",
        "internalType": "struct Types.UserRules",
        "components": [
          {
            "name": "maxSlippageBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minTradeAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "settlementAddress",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "targetTokens",
            "type": "address[]",
            "internalType": "address[]"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "smartAccount",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "proxiableUUID",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "redeploySmartAccount",
    "inputs": [],
    "outputs": [
      {
        "name": "smartAccount",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setStream",
    "inputs": [
      {
        "name": "smartAccount",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "superToken",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "rate",
        "type": "int96",
        "internalType": "int96"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setStreamCloseThreshold",
    "inputs": [
      {
        "name": "thresholdBps",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setSwapCooldown",
    "inputs": [
      {
        "name": "cooldownBlocks",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "smartAccountOf",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "streamCloseThresholdBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "swapCooldownBlocks",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "upgradeToAndCall",
    "inputs": [
      {
        "name": "newImplementation",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "userOf",
    "inputs": [
      {
        "name": "smartAccount",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "Initialized",
    "inputs": [
      {
        "name": "version",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Onboarded",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "smartAccount",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "superToken",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "underlyingAmountWrapped",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "superAmountMinted",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "rate",
        "type": "int96",
        "indexed": false,
        "internalType": "int96"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SmartAccountCreated",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "smartAccount",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SmartAccountRedeployed",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "oldSmartAccount",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newSmartAccount",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "StreamAutoClosed",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "smartAccount",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "superToken",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "availableBalance",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "deposit",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "StreamCloseThresholdUpdated",
    "inputs": [
      {
        "name": "thresholdBps",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "StreamUpdated",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "smartAccount",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "superToken",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "previousRate",
        "type": "int96",
        "indexed": false,
        "internalType": "int96"
      },
      {
        "name": "newRate",
        "type": "int96",
        "indexed": false,
        "internalType": "int96"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SwapCooldownUpdated",
    "inputs": [
      {
        "name": "cooldownBlocks",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SwapExecuted",
    "inputs": [
      {
        "name": "smartAccount",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "tokenIn",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "tokenOut",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amountIn",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "amountOut",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Upgraded",
    "inputs": [
      {
        "name": "implementation",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AddressEmptyCode",
    "inputs": [
      {
        "name": "target",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC1967InvalidImplementation",
    "inputs": [
      {
        "name": "implementation",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC1967NonPayable",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FORWARDER_NOT_SET",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FailedCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FailedDeployment",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INSUFFICIENT_OUTPUT",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_ADDRESS",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_AMOUNT",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_LABEL",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_LABEL_CHARS",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_RATE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_REPORT",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_RULES",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_SWAP_TOKEN",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_TARGET",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_THRESHOLD",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientBalance",
    "inputs": [
      {
        "name": "balance",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "needed",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidInitialization",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LABEL_TAKEN",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LABEL_TOO_LONG",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NAME_ALREADY_REGISTERED",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NAME_NOT_FOUND",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NOT_BOT",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NOT_OPERATOR",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NOT_OWNER",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NOT_SMART_ACCOUNT_OWNER",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NO_PRICE_SOURCE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NO_STREAM_TO_CLOSE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotInitializing",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ORACLE_DEVIATION",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "RATE_TOO_LOW",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RULES_NOT_SET",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SMART_ACCOUNT_ALREADY_EXISTS",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SMART_ACCOUNT_IMPL_NOT_SET",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SMART_ACCOUNT_NOT_FOUND",
    "inputs": []
  },
  {
    "type": "error",
    "name": "STALE_PRICE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "STREAM_NOT_ACTIVE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "STREAM_NOT_LOW",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SWAP_CALL_FAILED",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SWAP_COOLDOWN_ACTIVE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TARGET_TOKEN_NOT_ALLOWED",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TRADE_BELOW_MIN",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UNAUTHORIZED_CALLER",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UNSUPPORTED_UNDERLYING",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UUPSUnauthorizedCallContext",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UUPSUnsupportedProxiableUUID",
    "inputs": [
      {
        "name": "slot",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "WINDOW_TOO_LOW",
    "inputs": []
  }
] as const;
