// Auto-generated by scripts/sync-abis.mjs. Do not edit by hand.
export const streamVaultsConfigAbi = [
  {
    "type": "constructor",
    "inputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "MIN_ACCUMULATION_WINDOW",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "UPGRADE_INTERFACE_VERSION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "bot",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "cfaForwarder",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "initialize",
    "inputs": [
      {
        "name": "owner_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "bot_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "smartAccountImpl_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "permit2_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "swapRouter_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "oracle_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "cfaForwarder_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "minStreamAccumulationWindow_",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isAllowedTarget",
    "inputs": [
      {
        "name": "target",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isSupportedSwapToken",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minStreamAccumulationWindow",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "oracle",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "permit2",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "proxiableUUID",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setAllowedTarget",
    "inputs": [
      {
        "name": "target",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "allowed",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setBot",
    "inputs": [
      {
        "name": "newBot",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setCfaForwarder",
    "inputs": [
      {
        "name": "newForwarder",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMinStreamAccumulationWindow",
    "inputs": [
      {
        "name": "windowSeconds",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setOracle",
    "inputs": [
      {
        "name": "newOracle",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setPermit2",
    "inputs": [
      {
        "name": "newPermit2",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setSmartAccountImplementation",
    "inputs": [
      {
        "name": "newImpl",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setSupportedSwapToken",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "supported",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setSwapRouter",
    "inputs": [
      {
        "name": "newSwapRouter",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "smartAccountImplementation",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "swapRouter",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "upgradeToAndCall",
    "inputs": [
      {
        "name": "newImplementation",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "event",
    "name": "BotUpdated",
    "inputs": [
      {
        "name": "previousBot",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newBot",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CfaForwarderUpdated",
    "inputs": [
      {
        "name": "previousForwarder",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newForwarder",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Initialized",
    "inputs": [
      {
        "name": "version",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MinStreamAccumulationWindowUpdated",
    "inputs": [
      {
        "name": "previousWindow",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "newWindow",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OracleUpdated",
    "inputs": [
      {
        "name": "previousOracle",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOracle",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Permit2Updated",
    "inputs": [
      {
        "name": "previousPermit2",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newPermit2",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SmartAccountImplementationUpdated",
    "inputs": [
      {
        "name": "previousImpl",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newImpl",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SwapRouterUpdated",
    "inputs": [
      {
        "name": "previousSwapRouter",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newSwapRouter",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SwapTokenSupportUpdated",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "supported",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TargetWhitelistUpdated",
    "inputs": [
      {
        "name": "target",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "allowed",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Upgraded",
    "inputs": [
      {
        "name": "implementation",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AddressEmptyCode",
    "inputs": [
      {
        "name": "target",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC1967InvalidImplementation",
    "inputs": [
      {
        "name": "implementation",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC1967NonPayable",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FORWARDER_NOT_SET",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FailedCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INSUFFICIENT_OUTPUT",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_ADDRESS",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_AMOUNT",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_LABEL",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_LABEL_CHARS",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_RATE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_REPORT",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_RULES",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_SWAP_TOKEN",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_TARGET",
    "inputs": []
  },
  {
    "type": "error",
    "name": "INVALID_THRESHOLD",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidInitialization",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LABEL_TAKEN",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LABEL_TOO_LONG",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NAME_ALREADY_REGISTERED",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NAME_NOT_FOUND",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NOT_BOT",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NOT_OPERATOR",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NOT_OWNER",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NOT_SMART_ACCOUNT_OWNER",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NO_PRICE_SOURCE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NO_STREAM_TO_CLOSE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotInitializing",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ORACLE_DEVIATION",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "RATE_TOO_LOW",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RULES_NOT_SET",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SMART_ACCOUNT_ALREADY_EXISTS",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SMART_ACCOUNT_IMPL_NOT_SET",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SMART_ACCOUNT_NOT_FOUND",
    "inputs": []
  },
  {
    "type": "error",
    "name": "STALE_PRICE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "STREAM_NOT_ACTIVE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "STREAM_NOT_LOW",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SWAP_CALL_FAILED",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SWAP_COOLDOWN_ACTIVE",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TARGET_TOKEN_NOT_ALLOWED",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TRADE_BELOW_MIN",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UNAUTHORIZED_CALLER",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UNSUPPORTED_UNDERLYING",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UUPSUnauthorizedCallContext",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UUPSUnsupportedProxiableUUID",
    "inputs": [
      {
        "name": "slot",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "WINDOW_TOO_LOW",
    "inputs": []
  }
] as const;
